"""empty message

Revision ID: 1184095db8a5
Revises: ce744402ba28
Create Date: 2020-02-24 11:20:47.104669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1184095db8a5'
down_revision = 'ce744402ba28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Card', sa.Column('expiration', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Card', 'expiration')
    # ### end Alembic commands ###
