"""empty message

Revision ID: 15b2356b54bf
Revises: f8c13097be13
Create Date: 2020-05-25 14:46:12.802869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b2356b54bf'
down_revision = 'f8c13097be13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_feature',
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['Feature.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['Plan.id'], )
    )
    op.drop_table('feature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='feature_pkey')
    )
    op.drop_table('plan_feature')
    op.drop_table('Feature')
    # ### end Alembic commands ###
