"""Add send_tax_reciept flasg to customer

Revision ID: 28f74cb10e35
Revises: f3bdf790db9b
Create Date: 2020-08-10 14:53:05.732193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f74cb10e35'
down_revision = 'f3bdf790db9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Customer', sa.Column('send_tax_reciept', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Customer', 'send_tax_reciept')
    # ### end Alembic commands ###
