"""empty message

Revision ID: 3af6af05179d
Revises: 1184095db8a5
Create Date: 2020-02-24 16:20:10.037981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af6af05179d'
down_revision = '1184095db8a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Charity', sa.Column('last_plan_payment', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Charity', 'last_plan_payment')
    # ### end Alembic commands ###
