"""empty message

Revision ID: 3d59da326c2d
Revises: 106c680234d2
Create Date: 2020-03-11 14:42:03.876513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d59da326c2d'
down_revision = '106c680234d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Charity', sa.Column('business_name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Charity', 'business_name')
    # ### end Alembic commands ###
