"""empty message

Revision ID: 414ede9f841a
Revises: cf91f402435d
Create Date: 2020-03-10 13:06:40.338444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414ede9f841a'
down_revision = 'cf91f402435d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'BasiqInstitution', ['bank_id'])
    op.create_unique_constraint(None, 'TransactionDonation', ['bq_transaction_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TransactionDonation', type_='unique')
    op.drop_constraint(None, 'BasiqInstitution', type_='unique')
    # ### end Alembic commands ###
