"""empty message

Revision ID: 4c6316c398ac
Revises: f9bd812e28f4
Create Date: 2020-03-03 14:32:08.509933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6316c398ac'
down_revision = 'f9bd812e28f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Customer', 'bq_connection_id')
    op.drop_column('User', 'fp_customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('fp_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('Customer', sa.Column('bq_connection_id', sa.VARCHAR(length=127), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
