"""empty message

Revision ID: 4e6712165232
Revises: e040fe2278c0
Create Date: 2020-05-14 15:34:35.335246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6712165232'
down_revision = 'e040fe2278c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WeeklyDonation', sa.Column('stripe_transfer_id', sa.String(length=63), nullable=True))
    op.drop_column('WeeklyDonation', 'fp_direct_credit_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WeeklyDonation', sa.Column('fp_direct_credit_id', sa.VARCHAR(length=63), autoincrement=False, nullable=True))
    op.drop_column('WeeklyDonation', 'stripe_transfer_id')
    # ### end Alembic commands ###
