"""empty message

Revision ID: 5369c23049e4
Revises: c0fa44b73e57
Create Date: 2020-02-28 13:58:52.724711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5369c23049e4'
down_revision = 'c0fa44b73e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ParentCategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Category', sa.Column('parent_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Category', 'ParentCategory', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Category', type_='foreignkey')
    op.drop_column('Category', 'parent_id')
    op.drop_table('ParentCategory')
    # ### end Alembic commands ###
