"""empty message

Revision ID: 5be899aa9140
Revises: 4c6316c398ac
Create Date: 2020-03-03 17:15:24.862163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be899aa9140'
down_revision = '4c6316c398ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Customer', sa.Column('bq_connection_id', sa.String(length=127), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Customer', 'bq_connection_id')
    # ### end Alembic commands ###
