"""empty message

Revision ID: 603a270b751f
Revises: 15b2356b54bf
Create Date: 2020-05-25 15:09:10.043212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603a270b751f'
down_revision = '15b2356b54bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_features',
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['Feature.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['Plan.id'], )
    )
    op.drop_table('plan_feature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_feature',
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feature_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['Feature.id'], name='plan_feature_feature_id_fkey'),
    sa.ForeignKeyConstraint(['plan_id'], ['Plan.id'], name='plan_feature_plan_id_fkey')
    )
    op.drop_table('plan_features')
    # ### end Alembic commands ###
