"""empty message

Revision ID: 66e8d4024a3e
Revises: 99ff16f5b063
Create Date: 2020-05-12 19:33:12.130520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66e8d4024a3e'
down_revision = '99ff16f5b063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=31), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('cvc', sa.String(length=11), nullable=True),
    sa.Column('expiration', sa.String(length=7), nullable=True),
    sa.Column('stripe_card_id', sa.String(length=31), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('CharityCard')
    op.drop_table('CustomerCard')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CustomerCard',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"CustomerCard_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(length=31), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cvc', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('expiration', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('fp_token', sa.VARCHAR(length=31), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Customer.id'], name='CustomerCard_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='CustomerCard_pkey')
    )
    op.create_table('CharityCard',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"CharityCard_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(length=31), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cvc', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('expiration', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('fp_token', sa.VARCHAR(length=31), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Charity.id'], name='CharityCard_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='CharityCard_pkey')
    )
    op.drop_table('Card')
    # ### end Alembic commands ###
