"""empty message

Revision ID: 7222a30d43e1
Revises: 5be899aa9140
Create Date: 2020-03-04 23:35:55.259291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7222a30d43e1'
down_revision = '5be899aa9140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Customer', 'device_token',
               existing_type=sa.VARCHAR(length=127),
               type_=sa.String(length=511),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Customer', 'device_token',
               existing_type=sa.String(length=511),
               type_=sa.VARCHAR(length=127),
               existing_nullable=True)
    # ### end Alembic commands ###
