"""empty message

Revision ID: affc255178e3
Revises: e2f76218040f
Create Date: 2020-02-13 15:59:24.695967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'affc255178e3'
down_revision = 'e2f76218040f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TransactionDonation', 'bq_transaction_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TransactionDonation', sa.Column('bq_transaction_id', sa.VARCHAR(length=31), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
