"""empty message

Revision ID: c0fa44b73e57
Revises: feeadb3ebee4
Create Date: 2020-02-28 13:07:58.099905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0fa44b73e57'
down_revision = 'feeadb3ebee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Category', 'name',
               existing_type=postgresql.ENUM('HEALTH', 'CHILDREN', 'ANIMALS', 'PLANET', name='categoryname'),
               type_=sa.String(length=63),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Category', 'name',
               existing_type=sa.String(length=63),
               type_=postgresql.ENUM('HEALTH', 'CHILDREN', 'ANIMALS', 'PLANET', name='categoryname'),
               existing_nullable=False)
    # ### end Alembic commands ###
