"""empty message

Revision ID: ce744402ba28
Revises: 014e1fbd56a6
Create Date: 2020-02-21 11:14:45.953060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce744402ba28'
down_revision = '014e1fbd56a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('HEALTH', 'CHILDREN', 'ANIMALS', 'PLANET', name='categoryname'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Charity', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Charity', 'Category', ['category_id'], ['id'])
    op.drop_column('Charity', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Charity', sa.Column('category', sa.VARCHAR(length=127), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Charity', type_='foreignkey')
    op.drop_column('Charity', 'category_id')
    op.drop_table('Category')
    # ### end Alembic commands ###
