"""empty message

Revision ID: cf91f402435d
Revises: 7222a30d43e1
Create Date: 2020-03-06 17:47:28.748265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf91f402435d'
down_revision = '7222a30d43e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BasiqInstitution', sa.Column('logo', sa.String(length=255), nullable=True))
    op.drop_column('BasiqInstitution', 'logo_full')
    op.drop_column('BasiqInstitution', 'logo_square')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BasiqInstitution', sa.Column('logo_square', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('BasiqInstitution', sa.Column('logo_full', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('BasiqInstitution', 'logo')
    # ### end Alembic commands ###
