"""empty message

Revision ID: e2f76218040f
Revises: 
Create Date: 2020-02-12 15:29:37.591217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f76218040f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BasiqToken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=1023), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=1023), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('fp_payment_plan_id', sa.String(length=31), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=127), nullable=False),
    sa.Column('pwd_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('fp_customer_id', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('CUSTOMER', 'CHARITY', name='usertype'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=31), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('cvc', sa.String(length=11), nullable=True),
    sa.Column('fp_token', sa.String(length=31), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Charity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abn', sa.String(length=15), nullable=True),
    sa.Column('is_acnc', sa.Boolean(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=127), nullable=True),
    sa.Column('category', sa.String(length=127), nullable=True),
    sa.Column('details', sa.String(length=511), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['Plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=127), nullable=True),
    sa.Column('last_name', sa.String(length=127), nullable=True),
    sa.Column('weekly_goal', sa.Integer(), nullable=True),
    sa.Column('bq_user_id', sa.String(length=127), nullable=True),
    sa.Column('bq_connection_id', sa.String(length=127), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BankAccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('fp_account_id', sa.String(length=31), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('bsb', sa.String(length=11), nullable=False),
    sa.Column('number', sa.String(length=31), nullable=False),
    sa.ForeignKeyConstraint(['charity_id'], ['Charity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CustomerCharity',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['Charity.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['Customer.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'charity_id')
    )
    op.create_table('WeeklyDonation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('fp_direct_credit_id', sa.String(length=31), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'PENDING', 'COMPLETED', 'REJECTED', 'DELETED', name='directstatus'), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['Charity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TransactionDonation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('bq_transaction_id', sa.String(length=31), nullable=False),
    sa.Column('weekly_donation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['Charity.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['Customer.id'], ),
    sa.ForeignKeyConstraint(['weekly_donation_id'], ['WeeklyDonation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TransactionDonation')
    op.drop_table('WeeklyDonation')
    op.drop_table('CustomerCharity')
    op.drop_table('BankAccount')
    op.drop_table('Customer')
    op.drop_table('Charity')
    op.drop_table('Card')
    op.drop_table('User')
    op.drop_table('Plan')
    op.drop_table('BasiqToken')
    # ### end Alembic commands ###
