"""empty message

Revision ID: eb9f78036132
Revises: fbc9b178fe82
Create Date: 2020-03-03 10:39:02.208435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9f78036132'
down_revision = 'fbc9b178fe82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BasiqInstitution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('shortName', sa.String(length=255), nullable=True),
    sa.Column('institutionType', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('serviceName', sa.String(length=255), nullable=True),
    sa.Column('serviceType', sa.String(length=255), nullable=True),
    sa.Column('loginIdCaption', sa.String(length=255), nullable=True),
    sa.Column('passwordCaption', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.String(length=255), nullable=True),
    sa.Column('authorization', sa.String(length=255), nullable=True),
    sa.Column('logo_square', sa.String(length=255), nullable=True),
    sa.Column('logo_full', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BasiqInstitution')
    # ### end Alembic commands ###
