"""empty message

Revision ID: f176760dc9f9
Revises: 603a270b751f
Create Date: 2020-05-27 08:55:50.850230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f176760dc9f9'
down_revision = '603a270b751f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EmailVerification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['Charity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Charity', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Charity', 'is_email_verified')
    op.drop_table('EmailVerification')
    # ### end Alembic commands ###
