"""empty message

Revision ID: f8c13097be13
Revises: 4e6712165232
Create Date: 2020-05-25 14:44:00.794261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c13097be13'
down_revision = '4e6712165232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('Plan', 'image')
    op.drop_column('Plan', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Plan', sa.Column('description', sa.VARCHAR(length=1023), autoincrement=False, nullable=True))
    op.add_column('Plan', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('feature')
    # ### end Alembic commands ###
