"""empty message

Revision ID: f9bd812e28f4
Revises: eb9f78036132
Create Date: 2020-03-03 12:46:32.112425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9bd812e28f4'
down_revision = 'eb9f78036132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BasiqInstitution', sa.Column('secondaryLoginIdCaption', sa.String(length=255), nullable=True))
    op.add_column('BasiqInstitution', sa.Column('securityCodeCaption', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BasiqInstitution', 'securityCodeCaption')
    op.drop_column('BasiqInstitution', 'secondaryLoginIdCaption')
    # ### end Alembic commands ###
