"""empty message

Revision ID: fbc9b178fe82
Revises: 5369c23049e4
Create Date: 2020-03-02 13:44:03.825167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc9b178fe82'
down_revision = '5369c23049e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Customer', sa.Column('device_token', sa.String(length=127), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Customer', 'device_token')
    # ### end Alembic commands ###
