"""empty message

Revision ID: feeadb3ebee4
Revises: 6d8ff731ee20
Create Date: 2020-02-27 17:04:39.179368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feeadb3ebee4'
down_revision = '6d8ff731ee20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Charity', 'details',
               existing_type=sa.VARCHAR(length=511),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('Charity', 'name',
               existing_type=sa.VARCHAR(length=127),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('WeeklyDonation', 'fp_direct_credit_id',
               existing_type=sa.VARCHAR(length=31),
               type_=sa.String(length=63),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('WeeklyDonation', 'fp_direct_credit_id',
               existing_type=sa.String(length=63),
               type_=sa.VARCHAR(length=31),
               existing_nullable=True)
    op.alter_column('Charity', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=127),
               existing_nullable=True)
    op.alter_column('Charity', 'details',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=511),
               existing_nullable=True)
    # ### end Alembic commands ###
